spring:
  config:
    import: "optional:configserver:"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/luckLottery
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ture

logging.level:
  org.hibernate.SQL: debug

oauth:
  kakao:
    app-id: ${KAKAO_APP_ID}
  google:
    app-id: ${GOOGLE_APP_ID}

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
